const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
const fs = require('node:fs/promises');
const runtime = process.env.QUESTMAKER_TEST_MODULES || path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
const { chromium } = require(path.join(runtime, 'playwright'));
const sharp = require(path.join(runtime, 'sharp'));

(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const errors = [];
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, acceptDownloads: true });
  page.on('pageerror', error => errors.push(error.message));
  let fileChoosers = 0;
  page.on('filechooser', () => fileChoosers++);
  const output = '/tmp/questmaker-qa';
  await fs.mkdir(output, { recursive: true });
  const color = async (selector, value) => page.locator(selector).evaluate((el, value) => { el.value = value; el.dispatchEvent(new Event('input', { bubbles: true })); }, value);
  const number = async (selector, value) => { if(await page.locator(selector).getAttribute('type')==='range') await page.locator(selector).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},String(value)); else await page.locator(selector).fill(String(value)); await page.locator(selector).dispatchEvent('change'); };
  const open = async type => { if (await page.locator('#editorView').isVisible()) await page.locator('#homeButton').click(); await page.locator(`[data-open="${type}"]`).click(); };
  const download = async (format, name) => {
    const expectedWidth = await page.locator('#sheet').evaluate(el => el.offsetWidth * 2);
    const expectedHeight = await page.locator('#sheet').evaluate(el => el.offsetHeight * 2);
    await page.locator('#exportButton').click();
    await page.locator('#exportFormat').selectOption(format);
    const waiting = page.waitForEvent('download', { timeout: 20000 });
    await page.locator('#downloadButton').click(); await page.locator('#saveExport').click(); await page.locator('#closeExportPreview').click();
    const item = await waiting;
    const file = path.join(output, name);
    await item.saveAs(file);
    const meta = await sharp(file).metadata();
    assert.equal(meta.width, expectedWidth);
    assert.equal(meta.height, expectedHeight, 'Export follows content height');
    assert.equal(meta.format, format === 'jpeg' ? 'jpeg' : format);
    const stats = await sharp(file).stats();
    assert(stats.channels.some(c => c.stdev > 10), 'Export must contain rendered content');
    return file;
  };
  try {
    await page.goto('file://' + path.resolve('index.html'));
    assert.equal(await page.locator('.template-card').count(), 4);
    assert.equal(await page.locator('.template-card button').count(), 0);
    await page.screenshot({ path: path.join(output, 'home-desktop.png'), fullPage: true });
    await open(1);
    assert.equal(await page.locator('#sheet .image-box').count(), 9);
    assert.equal((await page.locator('#sheet .respondent').innerText()).trim(), '填表人：');
    const header = await page.locator('#sheet').evaluate(el => [...el.children].slice(0, 2).map(x => x.dataset.text));
    assert.deepEqual(header, ['title', 'respondent']);
    assert.equal(await page.locator('#sheet .watermark').evaluate(el => getComputedStyle(el).textAlign), 'center');
    await page.locator('#sheet [data-text="title"]').fill('我的绘画问卷');
    await page.locator('#sheet [data-text="title"]').evaluate(el => { el.focus(); const r = document.createRange(); r.setStart(el.firstChild, 0); r.setEnd(el.firstChild, 2); const s = getSelection(); s.removeAllRanges(); s.addRange(r); document.dispatchEvent(new Event('selectionchange')); });
    await color('#textColor', '#ed3456');
    assert.equal(await page.locator('#sheet [data-text="title"] span').first().innerText(), '我的');
    await page.locator('#textStyle').selectOption('title2');
    await number('#rows', 2);
    assert.equal(await page.locator('#sheet .grid-cell').count(), 6);
    assert(await page.locator('#sheet [data-text="title"]').evaluate(el => el.classList.contains('text-title2')));
    assert.equal(await page.locator('#sheet [data-text="title"] span').first().evaluate(el => el.style.color), 'rgb(237, 52, 86)');
    await page.locator('#boxRatio').selectOption('3/4');
    const twoRows = await page.locator('#sheet').evaluate(el => el.offsetHeight);
    await number('#rows', 1);
    const oneRow = await page.locator('#sheet').evaluate(el => el.offsetHeight);
    assert(oneRow < twoRows - 200, 'Removing a row shortens the canvas');
    assert(oneRow < 820, 'Canvas is no longer padded to a minimum height');
    const footerGap = await page.locator('#sheet').evaluate(el => el.querySelector('.watermark').getBoundingClientRect().top - el.querySelector('.grid-body').getBoundingClientRect().bottom);
    assert(footerGap < 50, 'Watermark follows the content');
    await page.screenshot({ path: path.join(output, 'one-row-desktop.png'), fullPage: true });
    await download('png', 'one-row-export.png');
    await number('#rows', 2);
    assert.equal(await page.locator('#sheet').evaluate(el => el.offsetHeight), twoRows);

    await page.locator('#sheet [data-image="grid-1"]').click();
    assert.equal(fileChoosers, 0, 'Selecting a frame does not open the file picker');
    assert.equal(await page.locator('#sheet [data-image="grid-1"]').getAttribute('aria-pressed'), 'true');
    await color('#cellFill', '#ffee99');
    await page.locator('#imageShape [data-option="rounded"]').click();
    assert.equal(await page.locator('#sheet [data-image="grid-1"]').getAttribute('aria-pressed'), 'true');
    await page.locator('#addFrameText').click();
    await page.locator('#sheet [data-text="frame-grid-1"]').fill('框内文字');
    await page.locator('#sheet [data-image="grid-1"]').click({position:{x:12,y:12}});
    assert.equal(await page.locator('#sheet [data-image="grid-1"]').evaluate(el=>getComputedStyle(el).backgroundColor), 'rgb(255, 238, 153)');
    assert.equal(await page.locator('#addFrameText').innerText(), '添加文字');
    assert.equal(fileChoosers, 0);
    const fixture = await sharp({ create: { width: 100, height: 100, channels: 3, background: '#2498b0' } }).png().toBuffer();
    await page.locator('#sheet [data-image="grid-0"]').click();
    assert.equal(fileChoosers, 0);
    const chooserPromise = page.waitForEvent('filechooser');
    await page.locator('#replaceImage').click();
    await (await chooserPromise).setFiles({ name: 'test.png', mimeType: 'image/png', buffer: fixture });
    await page.locator('#sheet [data-image="grid-0"] img').waitFor();
    await page.locator('#imageShape [data-option="rounded"]').click();
    await page.locator('#imageFit').selectOption('contain');
    assert.equal(await page.locator('#sheet [data-text="frame-grid-1"]').innerText(), '框内文字');
    await page.screenshot({ path: path.join(output, 'grid-desktop.png'), fullPage: true });
    const samplePoints = await page.locator('#sheet [data-image="grid-0"]').evaluate(el => {
      const paper = document.querySelector('#sheet'), p = paper.getBoundingClientRect(), r = el.getBoundingClientRect(), scale = p.width / paper.offsetWidth;
      const x = (r.left - p.left + r.width / 2) / scale * 2;
      return { x: Math.round(x), centerY: Math.round((r.top - p.top + r.height / 2) / scale * 2), paddingY: Math.round((r.top - p.top) / scale * 2 + 12) };
    });
    const gridPNG = await download('png', 'grid-export.png');
    const pixel = await sharp(gridPNG).extract({ left: samplePoints.x, top: samplePoints.centerY, width: 1, height: 1 }).raw().toBuffer();
    assert.deepEqual([...pixel].slice(0, 3), [36, 152, 176], 'Uploaded image is rendered');
    const letterbox = await sharp(gridPNG).extract({ left: samplePoints.x, top: samplePoints.paddingY, width: 1, height: 1 }).raw().toBuffer();
    assert.deepEqual([...letterbox].slice(0, 3), [255, 255, 255], 'Contain keeps the image aspect ratio when exporting');
    await download('jpeg', 'grid-export.jpg');
    await download('webp', 'grid-export.webp');
    await page.locator('#undoButton').click();
    await page.locator('#redoButton').click();
    assert.equal(await page.locator('#sheet [data-image="grid-0"] img').count(), 1);
    await open(0);
    await page.locator('#sheet [data-image="rank-0-0"]').click();
    await color('#cellFill', '#e5d4ed');
    assert.equal(await page.locator('#sheet [data-image="rank-0-0"]').evaluate(el=>getComputedStyle(el).backgroundColor), 'rgb(229, 212, 237)');
    const before = await page.locator('#sheet [data-row="0"]').evaluate(el => el.offsetHeight);
    const divider = await page.locator('#sheet [data-divider="0"]').boundingBox();
    await page.mouse.move(divider.x + 200, divider.y + divider.height / 2); await page.mouse.down(); await page.mouse.move(divider.x + 200, divider.y + 40, { steps: 5 }); await page.mouse.up();
    assert((await page.locator('#sheet [data-row="0"]').evaluate(el => el.offsetHeight)) > before);
    await number('#cols', 2);
    assert.equal(await page.locator('#sheet .rank-cell').count(), 10);
    await open(2);
    await page.locator('#linkMode').click();
    await page.locator('#sheet [data-image="node-0"]').click();
    await page.locator('#sheet [data-image="node-3"]').click();
    assert.equal(await page.locator('#sheet .relation-edge').count(), 1);
    await number('#nodeCount', 12);
    assert.equal(await page.locator('#sheet .relation-node').count(), 12);
    await download('png', 'relation-export.png');
    await open(3);
    await color('[data-theme="0"]', '#ee9e55');
    assert.equal(await page.locator('#sheet .scale-track').first().evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(170, 170, 170)');
    assert.equal(await page.locator('#sheet .scale-knob').first().evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(238, 158, 85)');
    const range = page.locator('#sheet [data-scale="voice-0"]');
    await range.fill('80');
    await range.dispatchEvent('input');
    assert.equal(await page.locator('#sheet .scale-knob').first().evaluate(el => el.style.left), '80%');
    const checkbox = page.locator('#sheet [data-check="choices-0-0"]');
    await checkbox.click();
    assert.equal(await checkbox.getAttribute('aria-checked'), 'true');
    const aligned = await checkbox.evaluate(el => { const a = el.getBoundingClientRect(), b = el.nextElementSibling.getBoundingClientRect(); return Math.abs((a.y + a.height / 2) - (b.y + b.height / 2)) < 2 && b.x > a.x + a.width; });
    assert(aligned, 'Choice and label must be inline');
    await number('#optionCount', 4);
    assert.equal(await page.locator('#sheet .choice').count(), 8);
    await page.locator('[data-add-component="legend"]').click();
    assert.equal(await page.locator('#sheet .legend').count(), 2, JSON.stringify({errors, components:await page.locator('#sheet [data-component]').evaluateAll(els=>els.map(el=>el.dataset.component))}));
    await page.screenshot({ path: path.join(output, 'compat-desktop.png'), fullPage: true });
    await download('png', 'compat-export.png');
    const fullCompatHeight = await page.locator('#sheet').evaluate(el=>el.offsetHeight);
    await page.locator('#sheet [data-image="notes-0"]').click();
    await page.locator('#selectionProperties [data-delete-block="notes"]').click();
    assert((await page.locator('#sheet').evaluate(el=>el.offsetHeight)) < fullCompatHeight - 50, 'Deleting a component shortens the canvas');
    await page.locator('#undoButton').click();
    assert.equal(await page.locator('#sheet').evaluate(el=>el.offsetHeight), fullCompatHeight);
    for (const width of [390, 320]) {
      await page.setViewportSize({ width, height: 844 });
      for (let type = 0; type < 4; type++) {
        await open(type);
        await page.waitForTimeout(100);
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `No page overflow at ${width}, type ${type}`);
        const bounds = await page.locator('#sheet').boundingBox();
        assert(bounds.x >= 0 && bounds.x + bounds.width <= width + 1, 'Canvas fits viewport');
      }
      await page.locator('#sheet [data-check="choices-0-0"]').click();
      assert(await page.locator('#selectionProperties [aria-label="上移组件"]').isVisible());
      await page.locator('#selectionProperties [aria-label="上移组件"]').click();
      await page.locator('#toast').evaluate(el => el.hidden = true);
      await page.screenshot({ path: path.join(output, `compat-mobile-${width}.png`), fullPage: true });
    }
    await download('png', 'compat-mobile-export.png');
    if (await fs.stat('/tmp/questmaker-draft-preview.html').catch(() => null)) {
      await page.goto('file:///tmp/questmaker-draft-preview.html');
      const frame = page.frameLocator('iframe');
      for (let i = 0; i < 4; i++) { await frame.locator('.qm-template').nth(i).click(); assert(await frame.locator('.qm-editor').isVisible()); await frame.locator('.qm-brand').click(); }
      await frame.locator('.qm-template').nth(1).click();
      await frame.locator('#qm-arrangement').selectOption('2,2');
      assert.equal(await frame.locator('.qm-cell').count(), 4);
    }
    assert.equal(fileChoosers, 1, 'Only explicit import opened a file picker');
    assert.deepEqual(errors, []);
    console.log('PASS: four editors, rich text, upload, shapes, dividers, relations, checkboxes, neutral tracks, 3 export formats, 320/390px layout, inline draft.');
    console.log('Screenshots and exports:', output);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
